name: test_env
channels:
- conda-forge
dependencies:
# We pin freetype and matplotlib for the image comparison
- freetype=2.10
- matplotlib-base=3.5.1
- pytest
- pytest-mpl
- pytest-xdist
- pytest-rerunfailures
- pytest-instafail
- pooch
